Repository Umplify/xunit-dependency-injection, pull requests merged in 2024-01, with the labels that each got.

#221 Add remote calculator project and according tests
  .gitignore
  examples/Xunit.Microsoft.DependencyInjection.ExampleTests.CalculationService/GenericControllerDemo.http
  examples/Xunit.Microsoft.DependencyInjection.ExampleTests.CalculationService/Program.cs
  examples/Xunit.Microsoft.DependencyInjection.ExampleTests.CalculationService/Properties/launchSettings.json
  examples/Xunit.Microsoft.DependencyInjection.ExampleTests.CalculationService/Requests.cs
  examples/Xunit.Microsoft.DependencyInjection.ExampleTests.CalculationService/Xunit.Microsoft.DependencyInjection.ExampleTests.CalculationService.csproj
  examples/Xunit.Microsoft.DependencyInjection.ExampleTests.CalculationService/appsettings.json
  examples/Xunit.Microsoft.DependencyInjection.ExampleTests/CalculatorTests.cs
  examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Fixtures/CalculatorFixture.cs
  examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Fixtures/RemoteCalculatorFixture.cs
  examples/Xunit.Microsoft.DependencyInjection.ExampleTests/IntegrationTests.cs
  examples/Xunit.Microsoft.DependencyInjection.ExampleTests/RemoteCalculatorTests.cs
  examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Services/Calculator.cs
  examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Services/ICalculator.cs
  examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Services/RemoteCalculator.cs
  examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Xunit.Microsoft.DependencyInjection.ExampleTests.csproj
  src/Xunit.Microsoft.DependencyInjection.sln
Labels: tests

#225 Adopt primary constructor pattern where applicable
  examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Services/Calculator.cs
  examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Xunit.Microsoft.DependencyInjection.ExampleTests.csproj
  src/Abstracts/TestBed.cs
  src/Attributes/TestOrderAttribute.cs
  src/Logging/OutputLogger.cs
  src/Logging/OutputLoggerProvider.cs
Labels: dotnet8

#230 Update Xunit.Microsoft.DependencyInjection.ExampleTests.csproj #229
  examples/Xunit.Microsoft.DependencyInjection.ExampleTests/Xunit.Microsoft.DependencyInjection.ExampleTests.csproj
Labels: enhancement

#234 Bump the sdk version in the build pipelines #233
  azure-pipeline-PR.yml
  azure-pipelines.yml
Labels: ci/cd
